#!/bin/sh
#
unset HYPOSAT_DATA
export HYPOSAT_DATA="../data"

\cp ./hyposat-in.tele hypomod-in
\cp hyposat-parameter.tele.mod hyposat-parameter

../bin/hypomod

\diff hypomod-out hypomod-out.tele | more

\rm hypomod-in hyposat-parameter
exit
